services:
    # Postgres Database
    postgres:
        image: docker.io/postgres
        environment:
            - POSTGRES_PASSWORD=postgres_password
    #redis Database
    redis:
        image: docker.io/redis
        command: ["redis-server", "--protected-mode", "no"]
    #Express API server
    api:
        build: ./server
        image: docker.io/mrudula761/complex-api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    #Worker Service
    worker:
        build: ./worker
        image: docker.io/mrudula761/complex-worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    #React client
    client:
         build: ./client
         image: docker.io/mrudula761/complex-client
    #Nginx controller
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            context: ./nginx
        ports:
            - '8083:80'